kind: Service
apiVersion: v1
metadata: 
  name: exampleservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accesible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      #Port acessible outside cluster
      nodePort: 30002
  type: LoadBalancer


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myappdeployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: test/exampleapp:v1.0.0
          ports:
            - containerPort: 8080